[package]
name = "data-pods-utils"
version = "0.1.0"
authors = ["Kai Mast <kaimast@cs.cornell.edu>"]
edition = "2018"

[dependencies]
chrono = { version="0.4" }
log = { version="0.4" }
serde = { version="^1", features = ["derive"] }
serde_bytes = { version="0.11" }
